apiVersion: v1
kind: Pod
spec:
  containers:  
    - name: docker
      image: docker:19.03.1-dind 
      command: ["tail", "-f", "/dev/null"]
      imagePullPolicy: Always
      volumeMounts:
        - name: docker
          mountPath: /var/run/docker.sock 
  volumes:
    - name: docker
      hostPath:
        path: /var/run/docker.sock
